### ISSUE TITLE
Input action missing for left controller menu button

### ISSUE THREAD

**Issue by FireDragonGameStudio** [ExtendRealityLtd/Tilia.Input.UnityInputSystem#18]
Hi :)

## Is your feature request related to a problem?
There is no input action included for the left controller menu button on Oculus Quest touch controllers. This is not really related to a problem, but I just stumbled across this and thought I'll tell you right away.

## Describe the solution you'd like
Regarding to the Unity docs [https://docs.unity3d.com/Manual/xr_input.html](https://docs.unity3d.com/Manual/xr_input.html) the supported action would be **start** (when looking at the menu button line). I already tried to create the action/binding myself an can confirm it works on Oculus Quest 1 touch controllers (see following screenshot).

![CaptureLeftControllerStart](https://user-images.githubusercontent.com/23502690/145675944-98910ce9-c30a-4e3a-a92a-c8b621ad5ec3.PNG)

Haven't included the screenshots, for the Internal adjustments, to keep the post short. Hope this will be helpful.
Best regards :)

**Comment by thestonefox** [comment]
The included sample is just a generic XR sample, which includes the left hand menu button. This is called start on oculus so it doesn't work by default with the left hand menu.

This is why it's just a sample, to showcase what can be done, it cannot map every possible aspect as the vendors cannot be consistent across their mappings.

**Comment by FireDragonGameStudio** [comment]
Ah, I get it now. Thx for the clarification :)
