### ISSUE TITLE
UnityInputSystem.InputActionMappings.GenericXR --> RightPrimaryButton_Touch is mapped to Left Primary Button Touched

### ISSUE THREAD

**Issue by fschmidmichels** [ExtendRealityLtd/Tilia.Input.UnityInputSystem#56]
### Environment

* Code source: Packages
* Code version: 2.4.4
* Platform version: Unity 2021.3.18
* 3rd party dependencies: -

### Steps to reproduce

![grafik](https://github.com/ExtendRealityLtd/Tilia.Input.UnityInputSystem/assets/64133200/16ad04ce-3cc1-4240-836e-1772b4c1bff2)

### Expected behavior

Touch the Right Primary Button to set the Action

### Current behavior

The Left Primary Button Touch is setting the Action

**Comment by thestonefox** [comment]
PR https://github.com/ExtendRealityLtd/Tilia.Input.UnityInputSystem/pull/57
